REPUTATION-SETTINGS:
  INCREMENTED-MESSAGE: true
  DECREMENTED-MESSAGE: true

DEFAULT-REPUTATION: 1000

INCREMENT-REPUTATION-BY:
  KILL: 500
  KOTH: 5000
  CONQUEST: 20000
  CITADEL: 25000

DECREMENT-REPUTATION-BY:
  DEATH: 200

REPUTATION-VALUES-COLOR:
  - "1000;&7[&f&l{REPUTATION}&7]"
  - "1500;&7[&c&l{REPUTATION}&7]"
  - "2000;&7[&b&l{REPUTATION}&7]"

DATABASE:
  MONGO:
    HOST: "127.0.0.1"
    PORT: 27017
    DATABASE: ""
    AUTHENTICATION:
      ENABLED: false
      DATABASE: ''
      USERNAME: ''
      PASSWORD: ''